export const ADD_INGREDIENT =  'ADD_INGREDIENT';
export const REMOVE_INGREDIENT =  'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_ERROR = 'FETCH_ERROR'
export const IF_BURGER_BUILDED = 'IF_BURGER_BUILDED'



 export const START_ORDER = 'START_ORDER'
 export const ORDERED_SUCCESSFULLY = 'ORDERED_SUCCESSFULLY'
 export const ORDER_FAILED = 'ORDER_FAILED'
 

 export const START_FETCH_ORDER ='START_FETCH_ORDER'
 export const FETCH_ORDER_SUCCESSFULLY = 'FETCH_ORDER_SUCCESSFULLY'
 export const FETCH_ORDER_FAILED = 'FETCH_ORDER_FAILED'
 

 export const AUTH_START = 'AUTH_START'
 export const AUTH_SUCCESS = 'AUTH_SUCCESS'
 export const AUTH_FAIL = 'AUTH_FAIL'
 export const LOGOUT = 'LOGOUT'


 export const BACKDROP_SHOW = 'BACKDROP_SHOW'
 export const BACKDROP_CLOSE = 'BACKDROP_CLOSE'
 export const   ORDER_SUMMARY_SHOW =  'ORDER_SUMMARY_SHOW'